services:
  chrome:
    image: selenium/node-chrome:4.1.4-20220427
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.1.4-20220427
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ./source/assets/extensions/firefox:/usr/src/app/assets/extensions/firefox

  selenium-hub:
    image: selenium/hub:4.1.4-20220427
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

  db:
    image: postgres
    restart: unless-stopped
    container_name: homogenise_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=homogenise
    ports:
      - '5432:5432'
    volumes:
      - ./homogenise_db:/var/lib/postgresql/data
      - ./website/settings/init.sql:/docker-entrypoint-initdb.d/create_database.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 40

  web:
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '5000:5000'
    volumes:
      - ./website:/app/website
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    build:
      context: ./
      dockerfile: ./Dockerfile
